services:
  all-in-one:
    image: daveearley/hi.events-all-in-one:latest
    restart: always
    environment:
      - VITE_FRONTEND_URL=https://${DOMAIN}
      - APP_FRONTEND_URL=https://${DOMAIN}
      - VITE_API_URL_CLIENT=https://${DOMAIN}/api
      - VITE_API_URL_SERVER=http://localhost:8080/api
      - VITE_STRIPE_PUBLISHABLE_KEY
      - LOG_CHANNEL=stderr
      - QUEUE_CONNECTION=sync
      - APP_KEY
      - JWT_SECRET
      - FILESYSTEM_PUBLIC_DISK=public
      - FILESYSTEM_PRIVATE_DISK=local
      - APP_CDN_URL=https://${DOMAIN}/storage
      - APP_DISABLE_REGISTRATION
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - STRIPE_PUBLIC_KEY
      - STRIPE_SECRET_KEY
      - STRIPE_WEBHOOK_SECRET
      - MAIL_MAILER
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_FROM_ADDRESS
      - MAIL_FROM_NAME
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chaoshow-network
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - chaoshow_data:/var/lib/postgresql/data

networks:
  chaoshow-network:
    external: true

volumes:
  chaoshow_data: