[supervisord]
nodaemon=true
pidfile=/var/run/supervisord.pid
logfile=/var/www/html/storage/logs/supervisord.log

# [inet_http_server]
# port = app:9001
# username = root
# password = root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:php]
command=docker-php-entrypoint php-fpm # This is our main process so let us put it here

[include]
files=/etc/supervisor/conf.d/*.conf
